; cSpell:ignoreRegExp rainmeter|Jonatas|ICONSIZE|FONTSIZE

[rainmeter]
	author         = F4Jonatas
	update         = 1000
	accurateText   = 1

[metadata]
	name        = RainJIT-Network
	author      = F4Jonatas
	version     = 1.1
	license     = GPL v2.0 License
	information = RainJIT simple test skin.

[variables]
	@include   = #@#globals.inc
	@include2  = styles.inc

	SCALE      = 1
	WIDTH      = ( 400 * #SCALE# )
	HEIGHT     = ( 150 * #SCALE# )
	RADIUS     = 6
	MARGIN_TOP = 45




[netIn]
	measure       = netIn
	; updateDivider = 10

[netOut]
	measure       = netOut
	; updateDivider = 10

[lua]
	measure = plugin
	plugin  = RainJIT
	script  = script.lua


[body]
	meter         = shape
	shape         = rectangle 0, 0, #WIDTH#, #HEIGHT#, #RADIUS# | fill color #GLOBALS_DARK_BACKGROUND# | strokeWidth 0
	updateDivider = -1

[icon]
	meter          = string
	meterStyle     = paused | font-rFont | antialias | align-center
	fontSize       = 18
	y              = ( #MARGIN_TOP# / 2 )
	x              = 25
	h              = #MARGIN_TOP#
	text           = [\xE8BD]
	inlinePattern  = ^(.*)$
	inlineSetting  = shadow | 0 | 0.5 | 1 | 0,0,0,120
	inlinePattern2 = ^(.*)$
	inlineSetting2 = gradientColor | 90 | 220, 220, 220 ; 0.0 | 240, 240, 240 ; 0.8

[title]
	meter          = string
	meterStyle     = paused | font-rFont | antialias | align-left
	fontSize       = 12
	text           = "Network"
	y              = ( #MARGIN_TOP# / 2 )
	x              = 45
	h              = #MARGIN_TOP#
	inlinePattern  = ^(.*)$
	inlineSetting  = shadow | 0 | 0.5 | 1 | 0,0,0,120
	inlinePattern2 = ^(.*)$
	inlineSetting2 = gradientColor | 90 | 220, 220, 220 ; 0.0 | 255, 255, 255 ; 0.8
	inlinePattern3 = ^(.*)$
	inlineSetting3 = gradientColor | 90 | 220, 220, 220 ; 0.0 | 255, 255, 255 ; 0.8

[graphic]
	meter         = shape
	w             = #WIDTH#
	x             = 0
	y             = #MARGIN_TOP#
	; Download stroke
	shape         = path path | stroke linearGradient gradient
	path          = 0,0 | lineTo 0,0
	gradient      = 180 | 102,219,252,20 ; 0 | 102,219,252,180 ; 0.2 | 102,219,252,180 ; 0.85 | 102,219,252,20 ; 1
	; Download background
	shape2        = path path2 | strokeWidth 0 | fill linearGradient gradient2
	path2         = 0,0 | lineTo 0,0
	gradient2     = -90 | 102,219,252,86 ; 0 | 102,219,252,20 ; 1
	; Upload stroke
	shape3        = path path3 | stroke linearGradient gradient3 | strokeDashes 5,3 | strokeDashCap round
	path3         = 0,0 | lineTo 0,0
	gradient3     = 180 | 255,80,220,20 ; 0 | 255,80,220,255 ; 0.2 | 255,80,220,255 ; 0.85 | 255,80,220,20 ; 1
	; Bar yAxis
	shape4        = path path4 | stroke color 255,255,255,200 | strokeWidth 2
	path4         = ( #WIDTH# - 20 ),9 | lineTo ( #WIDTH# - 8 ),9 | lineTo ( #WIDTH# - 8 ), ( #HEIGHT# - #MARGIN_TOP# - 8 ) | lineTo ( #WIDTH# - 20 ), ( #HEIGHT# - #MARGIN_TOP# - 8 )
	; Border Current Value
	shape5        = rectangle ( 10 * #SCALE# ),( 35 * #SCALE# ), ( 70 * #SCALE# ),( 40 * #SCALE# ), 4 | fill color 255,0,0,20 | stroke color ff0000 | strokeWidth 2 | strokeDashes 30,110 | strokeDashOffset 30.0
	; shape5        = path path5 | stroke color ff0000 | strokeDashCap flat
	; path5         = ( 16 * #SCALE# ),( 35 * #SCALE# ) | lineTo ( 85 * #SCALE# ),( 35 * #SCALE# ) | lineTo ( 85 * #SCALE# ),( 75 * #SCALE# ) | lineTo ( 15 * #SCALE# ),( 75 * #SCALE# ) | lineTo ( 15 * #SCALE# ),( 34 * #SCALE# )
	updateDivider = -1

[value.Max]
	meter          = string
	meterStyle     = paused | text-white| font-rFont | antialias | align-right
	x              = ( #WIDTH# - 5 )
	y              = #MARGIN_TOP#
	fontSize       = 8

[value.Min]
	meter          = string
	meterStyle     = paused | text-white| font-rFont | antialias | align-right
	x              = ( #WIDTH# - 10 )
	y              = ( #HEIGHT# - 16 )
	fontSize       = 8
	Text           = "0 B"

[value]
	meter          = string
	meterStyle     = paused | text-white| font-rFont | antialias | align-right
	x              = ( 80  * #SCALE# )
	y              = ( 100 * #SCALE# )
	w              = ( 70  * #SCALE# )
	h              = ( 40  * #SCALE# )
	fontSize       = ( 9   * #SCALE# )
	; solidColor     = 0,255,0,10
