
[rainmeter]
	update          = 1000

[metadata]
	name        = Rain-Bundle
	author      = F4Jonatas
	version     = 1.1
	license     = GPL v2.0 License
	information = RainJIT simple test skin.

[variables]
	@include   = styles.inc

	WIDTH      = 960
	HEIGHT     = 540
	MARGIN_TOP = 45



[lua]
	measure    = plugin
	plugin     = RainJIT
	script     = script.lua



[body]
	meter         = shape
	shape         = rectangle 0,0, #WIDTH#, #HEIGHT# | fill color 0,0,0,180 | strokeWidth 0
	; shape2 = path paht1 | fill color ff0000
	; paht1 = 11.74,8.914|CurveTo 14.644,10.181,14.644,11.74|CurveTo 13.342,14.569,11.74,14.569|CurveTo 8.835,13.301,8.835,11.74|CurveTo 10.138,8.914,11.74,8.914|ClosePath 1|LineTo 11.74,15.87|CurveTo 15.945,14.016,15.945,11.74|CurveTo 14.058,7.613,11.74,7.613|CurveTo 7.533,9.465,7.533,11.74|CurveTo 9.421,15.87,11.74,15.87|ClosePath 1
	updateDivider = -1

[title]
	meter          = string
	meterStyle     = paused | font-rFont | antialias | align-left
	fontSize       = 12
	text           = "Skin Bundle"
	y              = ( #MARGIN_TOP# / 2 )
	x              = (( #WIDTH# /2 ) - ( [&title:W] / 2 ))
	h              = #MARGIN_TOP#
	inlinePattern  = ^(.*)$
	inlineSetting  = shadow | 0 | 0.5 | 1 | 0,0,0,120
	inlinePattern2 = ^(.*)$
	inlineSetting2 = gradientColor | 90 | 220, 220, 220 ; 0.0 | 255, 255, 255 ; 0.8
	DynamicVariables = 1

[icon]
	meter = image
	imagePath           = images\
	imageName           = icon
	preserveAspectRatio = 1
	updateDivider       = -1
	w = 30
	x = ( [&title:X] - [&icon:W] - 2 )
	y = 8
	DynamicVariables = 1
