
[rainmeter]
	update         = 5000
	backgroundMode = 2
	solidColor     = 0,0,0,100
	skinWidth      = #WIDTH#
	skinHeight     = #HEIGHT#


[metadata]
	name        = RainJIT-Weather
	author      = F4Jonatas
	version     = 1.4
	license     = GPL v2.0 License
	information = RainJIT simple test skin.



[variables]
	@Include   = styles.inc

	SCALE      = 1
	RADIUS     = 6
	MARGIN_TOP = 45
	WIDTH      = ( 332 * #SCALE# )
	HEIGHT     = ( 220 * #SCALE# )






[lua]
	measure = plugin
	plugin  = RainJIT
	script  = script.lua


[icon]
	meter          = string
	stringAlign    = centerCenter
	fontFace       = rFont
	antialias      = 1
	fontSize       = 18
	y              = ( #MARGIN_TOP# / 2 )
	x              = 25
	h              = #MARGIN_TOP#
	text           = [\xE8A5]
	inlinePattern  = ^(.*)$
	inlineSetting  = shadow | 0 | 0.5 | 1 | 0,0,0,120
	inlinePattern2 = ^(.*)$
	inlineSetting2 = gradientColor | 90 | 220, 220, 220 ; 0.0 | 240, 240, 240 ; 0.8
	updateDivider  = -1

[title]
	meter          = string
	stringAlign    = leftCenter
	fontSize       = 12
	antialias      = 1
	text           = "Weather"
	fontFace       = rFont
	y              = ( #MARGIN_TOP# / 2 )
	x              = 45
	h              = #MARGIN_TOP#
	inlinePattern  = ^(.*)$
	inlineSetting  = shadow | 0 | 0.5 | 1 | 0,0,0,120
	inlinePattern2 = ^(.*)$
	inlineSetting2 = gradientColor | 90 | 220, 220, 220 ; 0.0 | 255, 255, 255 ; 0.8
	inlinePattern3 = ^(.*)$
	inlineSetting3 = gradientColor | 90 | 220, 220, 220 ; 0.0 | 255, 255, 255 ; 0.8
	updateDivider = -1

[curText]
	meter         = string
	meterStyle    = texts | paused | align-left
	fontFace      = rFont
	fontColor     = 200, 200, 200
	fontSize      = ( 12 * #SCALE# )
	x             = ( 20 * #SCALE# )
	y             = ( 15 + #MARGIN_TOP# )
	updateDivider = -1

[curTemp]
	meter         = string
	meterStyle    = texts | paused | align-left
	fontFace      = rFont
	fontSize      = ( 45 * #SCALE# )
	x             = ( 15 * #SCALE# )
	y             = ( 30 + #MARGIN_TOP# )
	; inlinePattern  = ^(.*)$
	; inlineSetting  = shadow | -2 | -2 | 1 | 0,0,255,100
	; inlinePattern2 = ^(.*)$
	; inlineSetting2 = shadow | 2 | 2 | 1 | 255,0,0,100
	updateDivider = -1

[tempH1]
	meter         = string
	meterStyle    = texts | paused | font-E2B3B3
	fontSize      = ( 12 * #SCALE# )
	x             = ( #WIDTH# - ( 55 * #SCALE# ))
	y             = ((( #MARGIN_TOP# + 3 )) - ( 2 * #SCALE# ))
	updateDivider = -1

[tempH2]
	meter         = string
	meterStyle    = texts | paused | font-E2B3B3
	fontSize      = ( 12 * #SCALE# )
	x             = 0r
	y             = ( [icon2:Y] - ( 2 * #SCALE# ))
	updateDivider = -1

[tempH3]
	meter         = string
	meterStyle    = texts | paused | font-E2B3B3
	fontSize      = ( 12 * #SCALE# )
	x             = r
	y             = ( [icon3:Y] - ( 2 * #SCALE# ))
	updateDivider = -1

[tempH4]
	meter         = string
	meterStyle    = texts | paused | font-E2B3B3
	fontSize      = ( 12 * #SCALE# )
	x             = r
	y             = ( [icon4:Y] - ( 2 * #SCALE# ))
	updateDivider = -1

[tempL1]
	meter         = string
	meterStyle    = texts | paused | font-DAECFF
	fontSize      = ( 12 * #SCALE# )
	x             = r
	y             = ( [tempH1:Y] + [tempH1:H] - ( 6 * #SCALE# ))
	updateDivider = -1

[tempL2]
	meter         = string
	meterStyle    = texts | paused | font-DAECFF
	fontSize      = ( 12 * #SCALE# )
	x             = r
	y             = ( [tempH2:Y] + [tempH2:H] - ( 6 * #SCALE# ))
	updateDivider = -1

[tempL3]
	meter         = string
	meterStyle    = texts | paused | font-DAECFF
	fontSize      = ( 12 * #SCALE# )
	x             = r
	y             = ( [tempH3:Y] + [tempH3:H] - ( 6 * #SCALE# ))
	updateDivider = -1

[tempL4]
	meter         = string
	meterStyle    = texts | paused | font-DAECFF
	fontSize      = ( 12 * #SCALE# )
	x             = r
	y             = ( [tempH4:Y] + [tempH4:H] - ( 6 * #SCALE# ))
	updateDivider = -1

[week-day1]
	meter         = string
	meterStyle    = texts | paused | bold
	fontSize      = ( 9 * #SCALE# )
	x             = ( [tempH1:X] - 4 )
	y             = ( [icon1:Y] + ( 2 * #SCALE# ))
	updateDivider = -1

[week-day2]
	meter         = string
	meterStyle    = texts | paused | bold
	fontSize      = ( 9 * #SCALE# )
	x             = ( [tempH2:X] - 4 )
	y             = ( [icon2:Y] + ( 2 * #SCALE# ))
	updateDivider = -1

[week-day3]
	meter         = string
	meterStyle    = texts | paused | bold
	fontSize      = ( 9 * #SCALE# )
	x             = ( [tempH3:X] - 4 )
	y             = ( [icon3:Y] + ( 2 * #SCALE# ))
	updateDivider = -1

[week-day4]
	meter         = string
	meterStyle    = texts | paused | bold
	fontSize      = ( 9 * #SCALE# )
	x             = ( [tempH4:X] - 4 )
	y             = ( [icon4:Y] + ( 2 * #SCALE# ))
	updateDivider = -1

[phrase1]
	meter         = string
	meterStyle    = texts | paused | bold | clip-string
	fontSize      = ( 9 * #SCALE# )
	w             = ( #WIDTH# - ( 250 * #SCALE# ))
	x             = ( [tempH1:X] - 4 )
	y             = ( [week-day1:Y] + [week-day1:H] - ( 4 * #SCALE# ))
	updateDivider = -1

[phrase2]
	meter         = string
	meterStyle    = texts | paused | bold | clip-string
	fontSize      = ( 9 * #SCALE# )
	w             = ( #WIDTH# - ( 250 * #SCALE# ))
	x             = ( [tempH2:X] - 4 )
	y             = ( [week-day2:Y] + [week-day2:H] - ( 4 * #SCALE# ))
	updateDivider = -1

[phrase3]
	meter         = string
	meterStyle    = texts | paused | bold | clip-string
	fontSize      = ( 9 * #SCALE# )
	w             = ( #WIDTH# - ( 250 * #SCALE# ))
	x             = ( [tempH3:X] - 4 )
	y             = ( [week-day3:Y] + [week-day3:H] - ( 4 * #SCALE# ))
	updateDivider = -1

[phrase4]
	meter         = string
	meterStyle    = texts | paused | bold | clip-string
	fontSize      = ( 9 * #SCALE# )
	w             = ( #WIDTH# - ( 250 * #SCALE# ))
	x             = ( [tempH4:X] - 4 )
	y             = ( [week-day4:Y] + [week-day4:H] - ( 4 * #SCALE# ))
	updateDivider = -1

[icon1]
	meter         = image
	meterStyle    = icons | paused
	x             = ( #WIDTH# - ( 52 * #SCALE# ))
	y             = ( #MARGIN_TOP# + 3 )
	w             = ( 32 * #SCALE# )
	updateDivider = -1

[icon2]
	meter         = image
	meterStyle    = icons | paused
	x             = r
	y             = ( 8 * #SCALE# )R
	w             = ( 32 * #SCALE# )
	updateDivider = -1

[icon3]
	meter         = image
	meterStyle    = icons | paused
	x             = r
	y             = ( 8 * #SCALE# )R
	w             = ( 32 * #SCALE# )
	updateDivider = -1

[icon4]
	meter         = image
	meterStyle    = icons | paused
	x             = r
	y             = ( 8 * #SCALE# )R
	w             = ( 32 * #SCALE# )
	updateDivider = -1
