
[icons]
	imagePath     = #ROOTCONFIGPATH#Weather\img\WeatherIcons\
	imageName     = unknown
	imageAlpha    = 240

[texts]
	fontColor = ffffff
	stringEffect = shadow
	stringAlign = right
	fontEffectColor = 0,0,0,120
	stringStyle = normal
	fontFace = calibri
	antialias = 1

[clipString]
	clipString = 1

[align-left]
	stringAlign = left

[bold]
	stringStyle = bold

[fontSize-9]
	fontSize = 9

[fontSize-12]
	fontSize = 12

[font-E2B3B3]
	fontColor = E2B3B3

[font-DAECFF]
	fontColor = DAECFF

[paused]
	updateDivider = -1
