; cSpell:ignoreRegExp rainmeter|Jonatas|ICONSIZE|FONTSIZE

[rainmeter]
	author         = F4Jonatas
	update         = 50
	accurateText   = 1
	ContextTitle   = "Select a folder"
	ContextAction  = !commandMeasure lua "selectFolder()"
	ContextTitle2  = "Open Context Menu"
	ContextAction2 = !commandMeasure lua "contextMenu()"

[metadata]
	name        = RainJIT-Shortcut
	author      = F4Jonatas
	version     = 1.1
	license     = GPL v2.0 License
	information = RainJIT simple test skin.



[variables]
	@include  = #@#globals.inc

	SCALE    = 1
	WIDTH    = ( 150 * #SCALE# )
	HEIGHT   = ( 150 * #SCALE# )
	ICONSIZE = ( 32  * #SCALE# )
	FONTSIZE = ( 8   * #SCALE# )
	RADIUS   = 6



[lua]
	measure = plugin
	plugin  = RainJIT
	script  = lua\script.lua


[body]
	meter             = shape
	shape             = rectangle 0, 0, #WIDTH#, #HEIGHT#, #RADIUS# | fill color #GLOBALS_DARK_BACKGROUND# | strokeWidth 1 | stroke color 255, 255, 255, 1
	updateDivider     = -1
	mouseActionCursor = 1

; [icon]
; 	meter         = image
; 	w             = #ICONSIZE#
; 	h             = #ICONSIZE#
; 	x             = (( #WIDTH# - #ICONSIZE# ) / 2 )
; 	y             = ( #HEIGHT# * 0.05 )
; 	imageName     = #CURRENTPATH#icons/folder
; 	updateDivider = -1

[text]
	meter          = string
	x              = 15
	; ( FontSize * 2 )
	y              = ( 28 - ( 10 * 2 ))
	; ( FontSize * * 1.8 )
	h              = ( 10 * 1.8 )
	fontSize       = 10
	fontFace       = rFont
	text           = "Folder Storage"
	antialias      = 1
	stringAlign    = leftTop
	clipString     = 1
	updateDivider  = -1
	inlinePattern  = ^(.*)$
	inlineSetting  = shadow | 0 | 1 | 1 | 0,0,0
	inlinePattern2 = ^(.*)$
	inlineSetting2 = gradientColor | 90 | 220, 220, 220 ; 0.0 | 255, 255, 255 ; 0.8
	solidColor = ff000064
