; cSpell:ignoreRegExp rainmeter|Jonatas|ICONSIZE|FONTSIZE

[rainmeter]
	author               = F4Jonatas
	update               = 50
	rightMouseDownAction = !skinCustomMenu
	ContextTitle         = "Select a Folder"
	ContextAction        = !commandMeasure lua "selectFolder()"
	ContextTitle2        = "Default Menu"
	ContextAction2       = !skinMenu
	ContextTitle3        = "Open Context Menu"
	ContextAction3       = !commandMeasure lua "contextMenu()"

[metadata]
	name        = RainJIT-Shortcut
	author      = F4Jonatas
	version     = 1.1
	license     = GPL v2.0 License
	information = RainJIT simple test skin.



[variables]
	SCALE    = 1.5
	WIDTH    = ( 77 * #SCALE# )
	HEIGHT   = ( 55 * #SCALE# )
	ICONSIZE = ( 32 * #SCALE# )
	FONTSIZE = ( 8  * #SCALE# )
	RADIUS   = ( 6  * #SCALE# )




[lua]
	measure = plugin
	plugin  = RainJIT
	script  = lua\small.lua


[body]
	meter         = shape
	shape         = rectangle 0, 0, #WIDTH#, #HEIGHT#, #RADIUS# | fill color 0,0,0,130 | strokeWidth 1 | stroke color 255, 255, 255, 1
	updateDivider = -1

[icon]
	meter         = image
	w             = #ICONSIZE#
	h             = #ICONSIZE#
	x             = (( #WIDTH# - #ICONSIZE# ) / 2 )
	y             = ( #HEIGHT# * 0.05 )
	updateDivider = -1

[text]
	meter          = string
	padding        = 5, 0, 5, 0
	x              = ( #WIDTH# / 2 )
	y              = ( #HEIGHT# - ( #FONTSIZE# * 2 ))
	w              = ( #WIDTH# - 10 )
	fontSize       = #FONTSIZE#
	fontFace       = rFont
	antialias      = 1
	stringAlign    = centerTop
	clipString     = 1
	updateDivider  = -1
	inlinePattern  = ^(.*)$
	inlineSetting  = shadow | 0 | 1 | 1 | 0,0,0,255
	inlinePattern2 = ^(.*)$
	inlineSetting2 = shadow | 0 | 1 | 5 | 0,0,0,100
	inlinePattern3 = ^(.*)$
	inlineSetting3 = gradientColor | 90 | 220, 220, 220 ; 0.0 | 255, 255, 255 ; 0.8
