
[Variables]

;-------- Enter the number of stocks you want to track below -------------
NumberOfStocks=12

; #### Symbols -----------------------------------
; Find Symbols by going to http://www.cnbc.com then entering the stock/index name you want in the search box. When the page opens look in the top-left address window and make a note of EXACTLY what comes after https://www.cnbc.com/quotes/  If there is a Period "." after the backslash "/" you must include it. or it will not work.

;eg https://www.cnbc.com/quotes/TSLA  --> Symbol1=TSLA -----------------

;	Units = Number of Units held
;	BuyPrice = Per Unit Price of stock when bought

Symbol1=BT.A-GB
Units1=5
BuyPrice1=185.02

;----------------------------------
Symbol2=UKW-GB
Units2=80
BuyPrice2=134.39

;----------------------------------
Symbol3 = ERIC
Units3 = 4.23
BuyPrice3 = 8.3286052
Convert3 = 0.72

;----------------------------------
Symbol4=ORIT-GB
Units4=75
BuyPrice4=108.22

;----------------------------------
Symbol5=JAY-GB
Units5=4
BuyPrice5=11.18

;-----------------------------------
Symbol6=AWE-GB
Units6=12
BuyPrice6=458.85

;-----------------------------------
Symbol7=DARK-GB
Units7=11
BuyPrice7=621.45

;------------------------------------
Symbol8=SSIT-GB
Units8=0
BuyPrice8=113.25

;------------------------------------
Symbol9=TRIG-GB
Units9=0
BuyPrice9=133.00

;------------------------------------
Symbol10=DRX-GB
Units10=0
BuyPrice10=403.80

;------------------------------------
Symbol11=NOKIA-IT
Units11=0
BuyPrice11=5.26

;------------------------------------
Symbol12=GSF-GB
Units12=0
BuyPrice12=112.00
