
[rainmeter]
	author          = F4Jonatas
	update          = 1
	backgroundMode  = 2
	solidColor      = 0,0,0,100
	; onRefreshAction = !commandMeasure lua "upgrade()"


[metadata]
	name        = Rain-Wallhaven
	author      = F4Jonatas
	version     = 2.1
	license     = GPL v2.0 License
	information = RainJIT simple test skin.

[variables]
	SCALE      = 1
	WIDTH      = ( 432 * #SCALE# )
	HEIGHT     = ( 243  * #SCALE# )
	RADIUS     = 6
	MARGIN_TOP = 45




[lua]
	measure    = plugin
	plugin     = RainJIT
	script     = script.lua


[icon]
	meter          = string
	stringAlign    = centerCenter
	fontFace       = rFont
	antialias      = 1
	fontSize       = 18
	y              = ( #MARGIN_TOP# / 2 )
	x              = 25
	h              = #MARGIN_TOP#
	text           = [\xE89B]
	inlinePattern  = ^(.*)$
	inlineSetting  = shadow | 0 | 0.5 | 1 | 0,0,0,120
	inlinePattern2 = ^(.*)$
	inlineSetting2 = gradientColor | 90 | 220, 220, 220 ; 0.0 | 240, 240, 240 ; 0.8
	updateDivider  = -1

[title]
	meter          = string
	stringAlign    = leftCenter
	fontSize       = 12
	antialias      = 1
	text           = "Wallhaven"
	fontFace       = rFont
	y              = ( #MARGIN_TOP# / 2 )
	x              = 45
	h              = #MARGIN_TOP#
	inlinePattern  = ^(.*)$
	inlineSetting  = shadow | 0 | 0.5 | 1 | 0,0,0,120
	inlinePattern2 = ^(.*)$
	inlineSetting2 = gradientColor | 90 | 220, 220, 220 ; 0.0 | 255, 255, 255 ; 0.8
	inlinePattern3 = ^(.*)$
	inlineSetting3 = gradientColor | 90 | 220, 220, 220 ; 0.0 | 255, 255, 255 ; 0.8
	updateDivider  = -1

[container]
	meter                      = shape
	shape                      = rectangle 0, 0, #WIDTH#, #HEIGHT#, 6 | fill color 80, 80, 80 | strokeWidth 0
	y                          = #MARGIN_TOP#
	updateDivider              = -1
	leftMouseDoubleClickAction = !commandMeasure lua "doubleClick()"
	rightMouseUpAction         = !commandMeasure lua "openMenu()"
	mouseActionCursor = 0

[image-cover]
	meter               = image
	container           = container
	imagePath           = downloadfile\
	imageName           = thumb02
	group               = picture
	w                   = #WIDTH#
	preserveAspectRatio = 1
	updateDivider       = -1

[image-front]
	meter               = image
	container           = container
	imagePath           = downloadfile\
	imageName           = thumb01
	group               = picture
	w                   = #WIDTH#
	preserveAspectRatio = 1
	updateDivider       = -1
