[rainmeter]
	update          = 1000
	accurateText    = 1
	backgroundMode  = 2
	solidColor      = 0,0,0,130
	skinHeight      = #HEIGHT#
	skinWidth       = #WIDTH#

[metadata]
	name        = Rain-Rainmeter-Forum
	author      = F4Jonatas
	version     = 1.1
	license     = GPL v2.0 License
	information = RainJIT simple test skin.

[variables]
	@include   = settings.inc

	SCALE      = 1
	WIDTH      = ( 400 * #SCALE# )
	HEIGHT     = ( 225 * #SCALE# )
	RADIUS     = 6
	MARGIN_TOP = 45



[lua]
	measure    = plugin
	plugin     = RainJIT
	script     = script.lua


[icon]
	meter          = string
	stringAlign    = centerCenter
	fontFace       = rFont
	antialias      = 1
	fontSize       = 18
	y              = ( #MARGIN_TOP# / 2 )
	x              = 25
	h              = #MARGIN_TOP#
	text           = [\xE89B]
	inlinePattern  = ^(.*)$
	inlineSetting  = shadow | 0 | 0.5 | 1 | 0,0,0,120
	inlinePattern2 = ^(.*)$
	inlineSetting2 = gradientColor | 90 | 220, 220, 220 ; 0.0 | 240, 240, 240 ; 0.8
	updateDivider  = -1

[title]
	meter          = string
	stringAlign    = leftCenter
	fontSize       = ( 12 * #SCALE# )
	antialias      = 1
	text           = "Rainmeter Forums"
	fontFace       = rFont
	y              = ( #MARGIN_TOP# / 2 )
	x              = 45
	h              = #MARGIN_TOP#
	inlinePattern  = ^(.*)$
	inlineSetting  = shadow | 0 | 0.5 | 1 | 0,0,0,120
	inlinePattern2 = ^(.*)$
	inlineSetting2 = gradientColor | 90 | 220, 220, 220 ; 0.0 | 255, 255, 255 ; 0.8
	updateDivider  = -1




; [MeasureRainmeterRSS]
; Measure=Plugin
; Plugin=Plugins\WebParser
; URL=https://#MyName#:#MyPassword#@forum.rainmeter.net/feed.php?auth=http
; RegExp="(?siU)^(.*)$"
; UpdateRate=120
; ForceReload=1
; FinishAction=[!EnableMeasure MeasureLuaScript #CURRENTCONFIG#]


; [MeasureLuaScript]
; Measure=Script
; ScriptFile=scriptold.lua
; Disabled=1


; [MeterPanel1]
; Meter=Image
; X=5
; Y=43
; W=410
; H=19
; SolidColor=45,45,45,255

; [MeterPanel2]
; Meter=Image
; X=5
; Y=0R
; W=410
; H=19
; SolidColor=20,20,20,255

; [MeterPanel3]
; Meter=Image
; X=5
; Y=0R
; W=410
; H=19
; SolidColor=45,45,45,255

; [MeterPanel4]
; Meter=Image
; X=5
; Y=0R
; W=410
; H=19
; SolidColor=20,20,20,255

; [MeterPanel5]
; Meter=Image
; X=5
; Y=0R
; W=410
; H=19
; SolidColor=45,45,45,255

; [MeterPanel6]
; Meter=Image
; X=5
; Y=0R
; W=410
; H=19
; SolidColor=20,20,20,255

; [MeterPanel7]
; Meter=Image
; X=5
; Y=0R
; W=410
; H=19
; SolidColor=45,45,45,255

; [MeterPanel8]
; Meter=Image
; X=5
; Y=0R
; W=410
; H=19
; SolidColor=20,20,20,255

; [MeterPanel9]
; Meter=Image
; X=5
; Y=0R
; W=410
; H=19
; SolidColor=45,45,45,255

; [MeterPanel10]
; Meter=Image
; X=5
; Y=0R
; W=410
; H=19
; SolidColor=20,20,20,255


; [MeterNewImage]
; Meter=Image
; W=7
; H=7
; X=227
; Y=18
; SolidColor=#NewColor#

; [MeterNewText]
; Meter=String
; MeterStyle=TextStyle
; W=45
; X=4R
; Y=14
; FontColor=#NewColor#
; Text=New

; [MeterMyImage]
; Meter=Image
; W=7
; H=7
; X=285
; Y=18
; SolidColor=#MyColor#

; [MeterMyText]
; Meter=String
; MeterStyle=TextStyle
; W=45
; X=4R
; Y=14
; FontColor=#MyColor#
; Text=Mine

; [MeterWatchImage]
; Meter=Image
; W=7
; H=7
; X=345
; Y=18
; SolidColor=#WatchColor#

; [MeterWatchText]
; Meter=String
; MeterStyle=TextStyle
; W=45
; X=4R
; Y=14
; FontColor=#WatchColor#
; Text=Watch

; ; Panel contents

; [MeterNew1]
; Meter=Image
; W=7
; H=7
; X=9
; Y=49
; SolidColor=0,0,0,1

; [MeterMy1]
; Meter=Image
; W=7
; H=7
; X=4R
; Y=0r
; SolidColor=0,0,0,1

; [MeterWatch1]
; Meter=Image
; W=7
; H=7
; X=4R
; Y=0r
; SolidColor=0,0,0,1

; [MeterTitle1]
; Meter=String
; MeterStyle=TextStyle
; Y=-5r

; [MeterNew2]
; Meter=Image
; W=7
; H=7
; X=9
; Y=7R
; SolidColor=0,0,0,1

; [MeterMy2]
; Meter=Image
; W=7
; H=7
; X=4R
; Y=0r
; SolidColor=0,0,0,1

; [MeterWatch2]
; Meter=Image
; W=7
; H=7
; X=4R
; Y=0r
; SolidColor=0,0,0,1

; [MeterTitle2]
; Meter=String
; MeterStyle=TextStyle
; Y=-5r

; [MeterNew3]
; Meter=Image
; W=7
; H=7
; X=9
; Y=7R
; SolidColor=0,0,0,1

; [MeterMy3]
; Meter=Image
; W=7
; H=7
; X=4R
; Y=0r
; SolidColor=0,0,0,1

; [MeterWatch3]
; Meter=Image
; W=7
; H=7
; X=4R
; Y=0r
; SolidColor=0,0,0,1

; [MeterTitle3]
; Meter=String
; MeterStyle=TextStyle
; Y=-5r

; [MeterNew4]
; Meter=Image
; W=7
; H=7
; X=9
; Y=7R
; SolidColor=0,0,0,1

; [MeterMy4]
; Meter=Image
; W=7
; H=7
; X=4R
; Y=0r
; SolidColor=0,0,0,1

; [MeterWatch4]
; Meter=Image
; W=7
; H=7
; X=4R
; Y=0r
; SolidColor=0,0,0,1

; [MeterTitle4]
; Meter=String
; MeterStyle=TextStyle
; Y=-5r

; [MeterNew5]
; Meter=Image
; W=7
; H=7
; X=9
; Y=7R
; SolidColor=0,0,0,1

; [MeterMy5]
; Meter=Image
; W=7
; H=7
; X=4R
; Y=0r
; SolidColor=0,0,0,1

; [MeterWatch5]
; Meter=Image
; W=7
; H=7
; X=4R
; Y=0r
; SolidColor=0,0,0,1

; [MeterTitle5]
; Meter=String
; MeterStyle=TextStyle
; Y=-5r

; [MeterNew6]
; Meter=Image
; W=7
; H=7
; X=9
; Y=7R
; SolidColor=0,0,0,1

; [MeterMy6]
; Meter=Image
; W=7
; H=7
; X=4R
; Y=0r
; SolidColor=0,0,0,1

; [MeterWatch6]
; Meter=Image
; W=7
; H=7
; X=4R
; Y=0r
; SolidColor=0,0,0,1

; [MeterTitle6]
; Meter=String
; MeterStyle=TextStyle
; Y=-5r

; [MeterNew7]
; Meter=Image
; W=7
; H=7
; X=9
; Y=7R
; SolidColor=0,0,0,1

; [MeterMy7]
; Meter=Image
; W=7
; H=7
; X=4R
; Y=0r
; SolidColor=0,0,0,1

; [MeterWatch7]
; Meter=Image
; W=7
; H=7
; X=4R
; Y=0r
; SolidColor=0,0,0,1

; [MeterTitle7]
; Meter=String
; MeterStyle=TextStyle
; Y=-5r

; [MeterNew8]
; Meter=Image
; W=7
; H=7
; X=9
; Y=7R
; SolidColor=0,0,0,1

; [MeterMy8]
; Meter=Image
; W=7
; H=7
; X=4R
; Y=0r
; SolidColor=0,0,0,1

; [MeterWatch8]
; Meter=Image
; W=7
; H=7
; X=4R
; Y=0r
; SolidColor=0,0,0,1

; [MeterTitle8]
; Meter=String
; MeterStyle=TextStyle
; Y=-5r

; [MeterNew9]
; Meter=Image
; W=7
; H=7
; X=9
; Y=7R
; SolidColor=0,0,0,1

; [MeterMy9]
; Meter=Image
; W=7
; H=7
; X=4R
; Y=0r
; SolidColor=0,0,0,1

; [MeterWatch9]
; Meter=Image
; W=7
; H=7
; X=4R
; Y=0r
; SolidColor=0,0,0,1

; [MeterTitle9]
; Meter=String
; MeterStyle=TextStyle
; Y=-5r

; [MeterNew10]
; Meter=Image
; W=7
; H=7
; X=9
; Y=7R
; SolidColor=0,0,0,1

; [MeterMy10]
; Meter=Image
; W=7
; H=7
; X=4R
; Y=0r
; SolidColor=0,0,0,1

; [MeterWatch10]
; Meter=Image
; W=7
; H=7
; X=4R
; Y=0r
; SolidColor=0,0,0,1

; [MeterTitle10]
; Meter=String
; MeterStyle=TextStyle
; Y=-5r
