
[text-white]
	fontColor = 255,255,255,220

[text-gray]
	fontColor = 200,200,200,220

[paused]
	updateDivider = -1

[font-rFont]
	fontFace = rFont

[font-shadow]
	inlinePattern = ^(.*)$
	inlineSetting = shadow | 0 | 0.5 | 1 | 0,0,0,200

[antialias]
	antialias = 1

[align-center]
	stringAlign = centerCenter

[align-left]
	stringAlign = leftCenter

[align-right]
	stringAlign = rightCenter

[break-line]
	clipString  = 2
	clipStringW = ( #WIDTH# - 40 )
	clipStringH = 20

[cntnr]
	container = container
